### ISSUE TITLE
Add Support for Mobvoi TicWatch Pro (catfish)

### ISSUE THREAD

**Issue by C9Glax** [AsteroidOS/meta-smartwatch#11]
Just to summarize for now:
- [x] Boot
- [x] ADB
- [x] WiFi
- [x] Bluetooth
  - [x] Pairing
  - [x] Weather
  - [x] Find
  - [x] Notification
  - [x] Screenshot
  - [x] Time
    - [ ] Correct time on LCD
  - [ ] ❔ Calls
- [ ] Sensors
  - [x] Heartbeat
  - [ ] Steps
    - [ ] Fitness App (AsteroidOS general feature)
  - [x] Tap-To-Wake
  - [x] Automatic Screen Brightness (Ambient Light)
  - [ ] Tilt-To-Wake
  - [ ] Gyro
  - [x] Compass
- [x] Low Power LCD ([Reference](https://github.com/AsteroidOS/asteroid/issues/153#issuecomment-959901651))
  - [ ] Step Counter
 
### TODO Features
- [x] MTP
- [x] `opkg configure` bug (battery undefined%) AsteroidOS/asteroid#94 AsteroidOS/asteroid#95
- [ ] Hardware Buttons
  - [ ] Top Button atm un-/locking screen. Should/Could be "home" to watchface.
  - [ ] Bottom Button does nothing
- [ ] Automatic WiFi (To safe energy)

-------------------------------------------------------- ORIGINAL -------------------------------------------------------- 

Hello,
we spoke briefly on IRC and @jrtberlin said that it might be possible to create a port for my beloved Smartwatch.
@MagneFire pointed me to the progress of the Huawei Watch 2 (Issue AsteroidOS/asteroid#101 ) and to get things started (in the future) I got the Partitiontable for you:
```
total 0
drwxr-xr-x 2 root root 740 1970-01-01 06:11 .
drwxr-xr-x 3 root root 800 1970-01-01 06:11 ..
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 DDR -> /dev/block/mmcblk0p18
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 aboot -> /dev/block/mmcblk0p4
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 abootbak -> /dev/block/mmcblk0p5
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 boot -> /dev/block/mmcblk0p21
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 cache -> /dev/block/mmcblk0p24
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 cmnlib -> /dev/block/mmcblk0p27
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 cmnlibbak -> /dev/block/mmcblk0p28
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 config -> /dev/block/mmcblk0p34
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 devinfo -> /dev/block/mmcblk0p26
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 fsc -> /dev/block/mmcblk0p15
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 fsg -> /dev/block/mmcblk0p19
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 keymaster -> /dev/block/mmcblk0p29
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 keymasterbak -> /dev/block/mmcblk0p30
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 keystore -> /dev/block/mmcblk0p32
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 misc -> /dev/block/mmcblk0p13
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 modem -> /dev/block/mmcblk0p1
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 modemst1 -> /dev/block/mmcblk0p11
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 modemst2 -> /dev/block/mmcblk0p12
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 oem -> /dev/block/mmcblk0p33
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 pad -> /dev/block/mmcblk0p10
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 persist -> /dev/block/mmcblk0p23
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 recovery -> /dev/block/mmcblk0p25
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 rpm -> /dev/block/mmcblk0p6
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 rpmbak -> /dev/block/mmcblk0p7
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 sbl1 -> /dev/block/mmcblk0p2
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 sbl1bak -> /dev/block/mmcblk0p3
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 sec -> /dev/block/mmcblk0p20
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 splash -> /dev/block/mmcblk0p17
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 ssd -> /dev/block/mmcblk0p16
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 system -> /dev/block/mmcblk0p22
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 ticnv -> /dev/block/mmcblk0p14
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 tz -> /dev/block/mmcblk0p8
lrwxrwxrwx 1 root root  20 1970-01-01 06:11 tzbak -> /dev/block/mmcblk0p9
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 userdata -> /dev/block/mmcblk0p35
lrwxrwxrwx 1 root root  21 1970-01-01 06:11 vendor -> /dev/block/mmcblk0p31
```
Kind regards,

~~(edit the code formatting on GitHub sucks)~~

**Comment by locksmxth5839** [comment]
A quick update... the tilt-to-wake feature actually works now.

**Comment by locksmxth5839** [comment]
It works amazingly fine.

**Comment by LecrisUT** [comment]
@C9Glax, @locksmxth5839 What are your statuses with the watches? Beware of #84

**Comment by MagneFire** [comment]
Closing this issue as the main goal has been achieved.
Most current issues relate to missing features not specific to this port. We can create or look at the existing issues for this.

Device specific issues should now get their own dedicated issue.
